### ISSUE TITLE
possible timeout on mariadb start

### ISSUE THREAD

**Issue by m-witt** [plesk/centos2alma#142] opened 2023-09-12 13:27 UTC
**Describe the bug**
While the upgrade itself went smooth i got an error that `mariadb.service` could not get started in the final phase of the upgrade. I belive this to be an timing problem

```2023-09-05 23:17:09,464 - INFO - Do: starting plesk services!
2023-09-05 23:17:09,464 - INFO - Running: ['/usr/bin/systemctl', 'enable', 'mariadb.service', 'plesk-task-manager.service', 'plesk-web-socket.service', 'sw-cp-server.service', 'sw-engine.service']. Output:
2023-09-05 23:17:09,478 - INFO - Synchronizing state of mariadb.service with SysV service script with /usr/lib/systemd/systemd-sysv-install.
2023-09-05 23:17:09,479 - INFO - Executing: /usr/lib/systemd/systemd-sysv-install enable mariadb
2023-09-05 23:17:09,678 - INFO - Created symlink /etc/systemd/system/mysql.service → /usr/lib/systemd/system/mariadb.service.
2023-09-05 23:17:09,678 - INFO - Created symlink /etc/systemd/system/mysqld.service → /usr/lib/systemd/system/mariadb.service.
2023-09-05 23:17:09,678 - INFO - Created symlink /etc/systemd/system/multi-user.target.wants/mariadb.service → /usr/lib/systemd/system/mariadb.service.
2023-09-05 23:17:09,678 - INFO - Created symlink /etc/systemd/system/multi-user.target.wants/plesk-task-manager.service → /usr/lib/systemd/system/plesk-task-manager.service.
2023-09-05 23:17:09,678 - INFO - Created symlink /etc/systemd/system/multi-user.target.wants/plesk-web-socket.service → /usr/lib/systemd/system/plesk-web-socket.service.
2023-09-05 23:17:09,678 - INFO - Created symlink /etc/systemd/system/multi-user.target.wants/sw-cp-server.service → /usr/lib/systemd/system/sw-cp-server.service.
2023-09-05 23:17:09,679 - INFO - Created symlink /etc/systemd/system/multi-user.target.wants/sw-engine.service → /usr/lib/systemd/system/sw-engine.service.
2023-09-05 23:17:09,866 - INFO - Command '['/usr/bin/systemctl', 'enable', 'mariadb.service', 'plesk-task-manager.service', 'plesk-web-socket.service', 'sw-cp-server.service', 'sw-engine.service']' finished successfully
2023-09-05 23:17:09,866 - INFO - Running: ['/usr/bin/systemctl', 'start', 'mariadb.service', 'plesk-task-manager.service', 'plesk-web-socket.service', 'sw-cp-server.service', 'sw-engine.service']. Output:
2023-09-05 23:17:45,179 - INFO - Job for mariadb.service failed because the control process exited with error code.
2023-09-05 23:17:45,179 - INFO - See "systemctl status mariadb.service" and "journalctl -xe" for details.
2023-09-05 23:17:45,181 - ERROR - Command '['/usr/bin/systemctl', 'start', 'mariadb.service', 'plesk-task-manager.service', 'plesk-web-socket.service', 'sw-cp-server.service', 'sw-engine.service']' failed with return code 1
2023-09-05 23:17:45,182 - ERROR - Failed: starting plesk services!. The reason: Command '['/usr/bin/systemctl', 'start', 'mariadb.service', 'plesk-task-manager.service', 'plesk-web-socket.service', 'sw-cp-server.service', 'sw-engine.service']' returned non-zero exit status 1.
2023-09-05 23:17:46,327 - ERROR - centos2alma process has been failed. Error: Failed: starting plesk services!. The reason: Command '['/usr/bin/systemctl', 'start', 'mariadb.service', 'plesk-task-manager.service', 'plesk-web-socket.service', 'sw-cp-server.service', 'sw-engine.service']' returned non-zero exit status 1.
```

Right after the upgrade failed i looked into `systemctl status mariadb` and found the database to be running about 5 seconds later
```[root@abc123 ~] # systemctl status mariadb.service 
● mariadb.service - MariaDB 10.2.41 database server
   Loaded: loaded (/usr/lib/systemd/system/mariadb.service; enabled; vendor preset: disabled)
  Drop-In: /etc/systemd/system/mariadb.service.d
           └─limits.conf, migrated-from-my.cnf-settings.conf
   Active: active (running) since Tue 2023-09-05 23:17:51 CEST; 2min 32s ago
     Docs: man:mysqld(8)
           https://mariadb.com/kb/en/library/systemd/
  Process: 43458 ExecStartPost=/bin/sh -c systemctl unset-environment _WSREP_START_POSITION (code=exited, status=0/SUCCESS)
  Process: 42637 ExecStartPre=/bin/sh -c [ ! -e /usr/bin/galera_recovery ] && VAR= ||   VAR=`cd /usr/bin/..; /usr/bin/galera_recovery`; [ $? -eq 0 ]   && systemctl set-environment _WSREP_START_POSITION=$VAR || exit 1 (code=exited, status=0/SUCCESS)
  Process: 42610 ExecStartPre=/bin/sh -c systemctl unset-environment _WSREP_START_POSITION (code=exited, status=0/SUCCESS)
 Main PID: 42949 (mysqld)
   Status: "Taking your SQL requests now..."
    Tasks: 35 (limit: 4308)
   Memory: 675.8M
   CGroup: /system.slice/mariadb.service
           └─42949 /usr/sbin/mysqld --basedir=/usr

Sep 05 23:17:50 abc123.mydomain.xy systemd[1]: Starting MariaDB 10.2.41 database server...
Sep 05 23:17:51 abc123.mydomain.xy mysqld[42949]: 2023-09-05 23:17:51 140001338616128 [Warning] option 'ft_min_word_len': unsigned value 0 adjusted to 1
Sep 05 23:17:51 abc123.mydomain.xy mysqld[42949]: 2023-09-05 23:17:51 140001338616128 [Note] /usr/sbin/mysqld (mysqld 10.2.41-MariaDB) starting as process 42949 ...
Sep 05 23:17:51 abc123.mydomain.xy mysqld[42949]: 2023-09-05 23:17:51 140001338616128 [Warning] Could not increase number of max_open_files to more than 20000 (request: 96186)
Sep 05 23:17:51 abc123.mydomain.xy systemd[1]: Started MariaDB 10.2.41 database server.
```

In case im right, would it be possible to increase the timeout to 120 seconds for example ?
Also : I tried to upgrade the system again one day later without any changes and it went through without errors.

**Feedback archive**
[centos2alma_feedback.zip](https://github.com/plesk/centos2alma/files/12586822/centos2alma_feedback.zip)

**Comment by SandakovMM** [comment] 2023-09-13 08:32
As I can see, startup timeout for MariaDB  systemd module is 900 seconds for 10.2 installed from official repository:
```
# Set an explicit Start and Stop timeout of 900 seconds (15 minutes!)
# this is the same value as used in SysV init scripts in the past
# Galera might need a longer timeout, check the KB if you want to change this:
# https://mariadb.com/kb/en/library/systemd/#configuring-the-systemd-service-timeout
TimeoutStartSec=900
TimeoutStopSec=900
```
Additionaly, for the standard AlmaLinux8 MariaDB 10.3.35, the timeout is 300 seconds, that should be fine as well.
It appears that in this case, MariaDB 10.3.35 is only being installed after the startup of the services, which is not the expected behavior. I suspect that this may lead to issues during service startup since we trying to start an old version of MariaDB.
Therefore, I propose moving the installation of the expected MariaDB version 10.3 before starting Plesk services to address this problem.

**Comment by SandakovMM** [comment] 2023-09-18 11:58
Related PR is #143

**Comment by SandakovMM** [comment] 2023-09-18 12:06
I've merged the changes, and believe the problem should be resolved now. Please feel free to reopen the ticket if it's not.

**Closed by SandakovMM** 2023-09-18 12:06 UTC
Labels: bug
