### ISSUE TITLE
MOTD informs thatSomething went wrong during dist-upgrade by centos2alma.

### ISSUE THREAD

**Issue by lecneri** [plesk/centos2alma#267] opened 2024-06-02 04:36 UTC
After few tries updating, I thought I had successfully updated centos 2 alma. The painel is working fine, and seems fine and it is working fine so far. But After I ssh to server I got this message of MOTD
===============================================================================
Message from the Plesk dist-upgrader tool:

Something went wrong during dist-upgrade by centos2alma.
See the /var/log/plesk/centos2alma.log file for more information.
You can remove this message from the /etc/motd file.
===============================================================================

tail the log archive I saw this error 
2024-06-02 00:46:55,634 - ERROR - Command ['/usr/sbin/plesk', 'sbin', 'webstatmng', '--set-configs', '--stat-prog', 'awstats', '--domain-name', 'alertas.sergipegas.com.br'] failed with return code 1
2024-06-02 00:46:55,634 - ERROR - Command ['/usr/sbin/plesk', 'sbin', 'webstatmng', '--set-configs', '--stat-prog', 'awstats', '--domain-name', 'alertas.sergipegas.com.br'] failed with return code 1
2024-06-02 00:46:55,634 - ERROR - Failed: recreate awstat configuration files for domains. The reason: Command '['/usr/sbin/plesk', 'sbin', 'webstatmng', '--set-configs', '--stat-prog', 'awstats', '--domain-name', 'i-removed-domain-at-posting']' returned non-zero exit status 1.
2024-06-02 00:46:55,634 - ERROR - Failed: recreate awstat configuration files for domains. The reason: Command '['/usr/sbin/plesk', 'sbin', 'webstatmng', '--set-configs', '--stat-prog', 'awstats', '--domain-name', 'i-removed-domain-at-posting']' returned non-zero exit status 1.

2024-06-02 00:46:56,853 - DEBUG - Sent error report
2024-06-02 00:46:56,853 - DEBUG - Sent error report
2024-06-02 00:46:56,858 - DEBUG - Trying to send status of conversion by report-update utility '/root/parallels/report-update'
2024-06-02 00:46:56,858 - DEBUG - Trying to send status of conversion by report-update utility '/root/parallels/report-update'
2024-06-02 00:46:57,866 - ERROR - centos2alma process has failed. Error: Failed: recreate awstat configuration files for domains. The reason: Command '['/usr/sbin/plesk', 'sbin', 'webstatmng', '--set-configs', '--stat-prog', 'awstats', '--domain-name', 'i-removed-domain-at-posting']' returned non-zero exit status 1.
2024-06-02 00:46:57,866 - ERROR - centos2alma process has failed. Error: Failed: recreate awstat configuration files for domains. The reason: Command '['/usr/sbin/plesk', 'sbin', 'webstatmng', '--set-configs', '--stat-prog', 'awstats', '--domain-name', 'i-removed-domain-at-posting'
]' returned non-zero exit status 1.

**Feedback archive**
I noticed the akaspersky.cnf error, which I already fixed
[centos2alma_feedback.zip](https://github.com/user-attachments/files/15524167/centos2alma_feedback.zip)
*Please attach a feedback archive to the bug report.*
You could create it by calling `centos2alma --prepare-feedback`.
The archive will help us investigate the problem better and faster.

**Comment by SandakovMM** [comment] 2024-06-03 13:05
Hello,
It seems that there was a domain that used to use AWStats in the past, but no longer does. Also, AWStats was removed from the server before the conversion. This is likely the cause of the issue.
I will fix this in the upcoming release.

**Comment by lecneri** [comment] 2024-06-03 15:36
I executed this command in shell and it said it didn't have model file, I saw that in /etc/awstats had a .model.rpmsave renamed, executed the command again and it worked. But I don't know if there's any other step after this.

**Comment by SandakovMM** [comment] 2024-06-03 15:53
> But I don't know if there's any other step after this.
Yes, there are bunch of finishing steps after the awstats action. You could proceed with conversion by calling:
`/root/centos2alma --finish --state-dir /usr/local/psa/var/centos2alma --resume --verbose --log-file /var/log/plesk/centos2alma.log`

**Comment by SandakovMM** [comment] 2024-06-05 06:25
The issue should be resolved by #270. I am attaching the fixed version of centos2alma
[centos2alma.zip](https://github.com/user-attachments/files/15574079/centos2alma.zip)

**Closed by SandakovMM** 2024-06-05 06:25 UTC
Labels: bug
