### ISSUE TITLE
Actor target_userspace_creator unexpectedly terminated with exit code: 1 

### ISSUE THREAD

**Issue by Klaus-UR** [plesk/centos2alma#286] opened 2024-06-18 06:39 UTC
Actor target_userspace_creator unexpectedly terminated with exit code: 1 

[centos2alma_feedback.zip](https://github.com/user-attachments/files/15881504/centos2alma_feedback.zip)

**Comment by SandakovMM** [comment] 2024-10-07 06:47
The issue is likely due to inconsistencies in the leapp files after your previous conversion process was interrupted by a signal (perhaps termination or loss of your SSH connection). Therefore, the following attempt by leapp to execute a conversion failed while trying to remove the previous user space.
I believe the issue might be resolved with the new version of leapp included in centos2alma v1.4.2. To proceed with the conversion, please do the following:
1. `wget https://github.com/plesk/centos2alma/releases/download/v1.4.2/centos2alma-1.4.2.zip ; unzip centos2alma-1.4.2.zip`
2. `centos2alma --revert`
3. `centos2alma`

Feel free to reopen the issue if you continue to experience problems.

**Closed by SandakovMM** 2024-10-07 06:47 UTC
Labels: bug
