### ISSUE TITLE
Upgrade inhibited: Newest installed kernel not in use

### ISSUE THREAD

**Issue by Altidata-dev** [plesk/centos2alma#147] opened 2023-10-18 23:43 UTC
The upgrade fails with 
  The last installed kernel is not in use.
        The kernel version in use is '3.10.0-1160.99.1.el7.x86_64'. The last installed kernel version is '3.10.0-957.el7.x86_64'.

When I run uname -r I get:
uname -r
3.10.0-1160.99.1.el7.x86_64

**Comment by SandakovMM** [comment] 2023-10-19 06:33
Hello,
Could you please provide the version of the centos2alma tool?

**Comment by Altidata-dev** [comment] 2023-10-19 09:53
I used centos2alma-1.2.0

**Comment by SandakovMM** [comment] 2023-10-20 07:27
I've found the root cause of the problem. PR with fix is #148.
There is a [build of the tool with merged fix](https://github.com/plesk/centos2alma/suites/17439756344/artifacts/996748490), could you please check this out?

**Comment by m-witt** [comment] 2023-10-25 10:20
> I've found the root cause of the problem. PR with fix is #148. There is a [build of the tool with merged fix](https://github.com/plesk/centos2alma/suites/17439756344/artifacts/996748490), could you please check this out?

I belive i have hit the same bug in an upgrade yesterday.

        The last installed kernel is not in use.
        The kernel version in use is '3.10.0-1160.102.1.el7.x86_64'. The last installed kernel version is '3.10.0-1160.99.1.el7.x86_64'.
        Reboot the system to use the last installed kernel.

[root@abc123 ~] # uname -r
3.10.0-1160.102.1.el7.x86_64


I also used centos2alma v1.2.0 and was able to successfully upgrade the system with the patched build mentioned above.

**Comment by SandakovMM** [comment] 2023-10-25 11:22
> I also used centos2alma v1.2.0 and was able to successfully upgrade the system with the patched build mentioned above.
@m-witt, thank you very much.
I've [released centos2alma v1.2.1](https://github.com/plesk/centos2alma/releases/tag/v1.2.1) with the fix up. There shouldn't be such problem on it.

**Closed by SandakovMM** 2023-10-25 11:22 UTC
Labels: bug

**Comment by SandakovMM** [comment] 2023-10-26 12:33
Hm, maybe some publishing problem. I've redo the release
