### ISSUE TITLE
chrooted environment broken after upgrade

### ISSUE THREAD

**Issue by ManfredLan** [plesk/centos2alma#336] opened 2024-08-22 09:25 UTC
Not sure this is an actual bug, or to be expected, but I figured I let you know anyways. Version used was 1.4.0.

We have some customers using chrooted /bin/bash and we observed chrooted being broken after the upgrade to Alma8.
Login was not working neither SSH nor su with following error:

-: error while loading shared libraries: libtinfo.so.6: cannot open shared object file: No such file or directory

After some investigation we found, that there were still some files from CentOS7 linked, only way so far was to rebuild and add the needed commands afterwards with
./update-chroot.sh --rebuild
./update-chroot.sh --add ...
./update-chroot.sh --apply-all

This is a pain in the behind in case a customer has a lot of customizations.

![Bildschirmfoto 2024-08-21 um 09 47 18](https://github.com/user-attachments/assets/11c9f955-2003-4c50-aad7-f25969f90b1b)

**Comment by SandakovMM** [comment] 2024-09-03 10:40
I have reviewed the issue and am unsure how we will fix it on the centos2alma side. If I remember correctly, ./update-chroot.sh is a specific script from some knowledge base articles used to add extra utilities, libraries, etc., into a chroot environment. Since Plesk does not provide this script, we cannot be certain it exists on the centos2alma side. Therefore, it is unclear how we can use it.
So for now I could only suggest to use update-chroot.sh as an workaround for the problem

**Comment by ManfredLan** [comment] 2024-09-04 13:23
Hi, 
yes, the update-chroot.sh is a script by Plesk to modify the chroot -environment.
It seems like this problem also affects chroot created by Plesk (by activating chroot in the hosting options) and not only modified ones.

I understand, that this might be not even a centos2alma problem, maybe it should be mentioned as possible issue in the instructions.
Like I initially said, primarily I wanted to make you - and maybe others - aware of this possible problem, in one case it took a few weeks until the customer even ran into the broken chroot and it was confusing for everyone.

**Comment by vizovitin** [comment] 2024-10-04 13:54
Duplicate of https://github.com/plesk/debian11to12/issues/5 , at least w.r.t. SSH. This will be fixed in Plesk since 18.0.65, to be released approximately on 2024-10-29.

**Closed by vizovitin** 2024-10-04 13:54 UTC
Labels: bug, duplicate
